### ISSUE TITLE
Compser  could not be found in any version

### ISSUE THREAD

**Issue by Aibric** [cornernote/yii2-workflow-manager#10]
The requested package cornernote/yii2-workflow-manager could not be found in any version, there may be a typo in the package name.

**Comment by philippfrenzel** [comment]
for me it's working, any details why it fails, your composer version and the require statement?

**Comment by Aibric** [comment]
Hi @philippfrenzel  My composer version 1.2.2 


composer require cornernote/yii2-workflow-manager "*"

 Problem 1
    - The requested package cornernote/yii2-workflow-manager * is satisfiable by cornernote/yii2-workflow-manager[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by cornernote** [comment]
You'll need to add `"minimum-stability": "dev"` to your composer.json file before you install the package. 

I haven't made a release yet.

**Comment by philippfrenzel** [comment]
and because of the logs you send me, pls. install the fxp/composer plugin - pls. check yii2 installation guide

**Comment by Aibric** [comment]
My YII2 version is 2.0.10, the following is my configuration.Thank you! @cornernote and @philippfrenzel 
Really looking forward to the next version.
```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "filsh/yii2-oauth2-server": "*",
        "raoul2000/yii2-workflow": "*",
        "raoul2000/yii2-workflow-view": "*"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=n"
    }
}
```

**Comment by philippfrenzel** [comment]
Hey, you have the wrong require! It should be 
cornernote for the view instead of raoul2000!

And for the version, pls. add "dev-master" as version for the view;)

Hope this will fix your issue!

**Comment by Aibric** [comment]
Using the `>composer require cornernote/yii2-workflow-manager "dev-master"`  command line installation is successful, thank you very much. @philippfrenzel @cornernote
