### ISSUE TITLE
tag?

### ISSUE THREAD

**Issue by simocheccoli** [cornernote/yii2-workflow-manager#13]
Hi @cornernote, when do you think to release a tag?

**Comment by cornernote** [comment]
Will do one tomorrow when I'm in the office

**Comment by badbreze** [comment]
Great!

**Comment by simocheccoli** [comment]
Perfect!! ;)

**Comment by cornernote** [comment]
https://github.com/cornernote/yii2-workflow-manager/releases/tag/1.0.0
