### ISSUE TITLE
Need to include i18n message files in this project

### ISSUE THREAD

**Issue by softbread** [cornernote/yii2-workflow-manager#7]
Because the view rendering uses i18n, it would be good to have translate message in this project as part of Yii module. Otherwise, first time user will have an exception of `Unable To Locate Message Source For Category workflow`. 

The fix should be really simple in config:

```
        'i18n' => [
            'translations' => [
                'workflow' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@path_to_the_message_files',
                    'sourceLanguage' => 'en-US',
                    'fileMap' => [
                        'workflow' => 'workflow.php',
                    ],
                ],
            ],
        ],
```

**Comment by cornernote** [comment]
Hey @softbread,

I haven't really used the I18N stuff before.  Are you able to do a PR for it?
